transform_tolerance: 0.01
min_height: -0.05
max_height: 0.1

angle_min: -0.087
angle_max: 0.087
angle_increment: 0.0175
scan_time: 0.3333
range_min: 0.1
range_max: 1.5
use_inf: true

# Concurrency level, affects number of pointclouds queued for processing and number of threads used
# 0 : Detect number of cores
# 1 : Single threaded
# 2->inf : Parallelism level
concurrency_level: 1